### PR TITLE
增加enum类型，生成attr不区分类型都增加type

### PR DESCRIPTION
**Pull request by ColorRabbit**

### CODE REVIEW

**Comment by siburuxue** [comment]
在Entity同步字段到数据库的时候，orm/doctrine不支持enum
```log
In AbstractPlatform.php line 325:
                                                                                                       
  Unknown database type "enum" requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.
```

```shell
php bin/console doctrine-helper:mapping:import --ucfirst=true
php bin/console make:migration
php bin/console doctrine:migrations:migrate
```

**Comment by ColorRabbit** [comment]
需要在 config/packages/doctrine.yaml 下配置
可以看文档 https://symfony.com/doc/current/doctrine/dbal.html#registering-custom-mapping-types-in-the-schematool
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: 9.4
                mapping_types:
                    enum: string
```
 
以前的版本，我这边是这么操作的，现在好像删了mapping_types也是可以执行的，我试了下以前的项目
"doctrine/doctrine-bundle": "^2.2",
"doctrine/doctrine-migrations-bundle": "^3.0",
"doctrine/orm": "^2.8",
删除了 mapping_types 也是会报错


我这边用的最新的包版本
 "doctrine/dbal": "^3",
"doctrine/doctrine-bundle": "^2.12",
"doctrine/doctrine-migrations-bundle": "^3.3",
"doctrine/orm": "^3.2",

**Comment by siburuxue** [comment]
> 需要在 config/packages/doctrine.yaml 下配置 可以看文档 https://symfony.com/doc/current/doctrine/dbal.html#registering-custom-mapping-types-in-the-schematool
> 
> ```
> doctrine:
>     dbal:
>         default_connection: default
>         connections:
>             default:
>                 url: '%env(resolve:DATABASE_URL)%'
>                 server_version: 9.4
>                 mapping_types:
>                     enum: string
> ```
> 
> 以前的版本，我这边是这么操作的，现在好像删了mapping_types也是可以执行的，我试了下以前的项目 "doctrine/doctrine-bundle": "^2.2", "doctrine/doctrine-migrations-bundle": "^3.0", "doctrine/orm": "^2.8", 删除了 mapping_types 也是会报错
> 
> 我这边用的最新的包版本 "doctrine/dbal": "^3", "doctrine/doctrine-bundle": "^2.12", "doctrine/doctrine-migrations-bundle": "^3.3", "doctrine/orm": "^3.2",

添加mapping_types之后同步数据库成功。已修改
```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            enum: string
```

**Comment by siburuxue** [comment]
> 需要在 config/packages/doctrine.yaml 下配置 可以看文档 https://symfony.com/doc/current/doctrine/dbal.html#registering-custom-mapping-types-in-the-schematool
> 
> ```
> doctrine:
>     dbal:
>         default_connection: default
>         connections:
>             default:
>                 url: '%env(resolve:DATABASE_URL)%'
>                 server_version: 9.4
>                 mapping_types:
>                     enum: string
> ```
> 
> 以前的版本，我这边是这么操作的，现在好像删了mapping_types也是可以执行的，我试了下以前的项目 "doctrine/doctrine-bundle": "^2.2", "doctrine/doctrine-migrations-bundle": "^3.0", "doctrine/orm": "^2.8", 删除了 mapping_types 也是会报错
> 
> 我这边用的最新的包版本 "doctrine/dbal": "^3", "doctrine/doctrine-bundle": "^2.12", "doctrine/doctrine-migrations-bundle": "^3.3", "doctrine/orm": "^3.2",

下次改代码的时候把readme也改一下

**Pull request closed without merging**
